// <auto-generated />
namespace Locadora.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_Disponivel_Filme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_Disponivel_Filme));
        
        string IMigrationMetadata.Id
        {
            get { return "202212172133490_add_Disponivel_Filme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
