// <auto-generated />
namespace Locadora.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_filme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_filme));
        
        string IMigrationMetadata.Id
        {
            get { return "202212171712415_add_filme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
